version: '3'
services:
  virtual-env:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./src:/home/kenta/src
    tty: true
    env_file:
      - .secret